### ISSUE TITLE
音量🔊无法调节，按钮位置不太对

### ISSUE THREAD

**Issue by tarvos21** [OTOMariK/yee_player#1]
很棒的设计，我在macOS上编译成功，试了播放mp3，能够播放音乐🎵，但音量条和速度条无法拖动，只能拖动进度条，不知道什么问题

**Comment by OTOMariK** [comment]
感谢反馈，我是个业余小白，只用过windows系统，没有macOS机器，想不到有什么办法能具体了解rust写的程序在macOS上的运行情况，很抱歉不知道怎样才能帮到你。

**Comment by tarvos21** [comment]
谢谢🙏
